version: '3.8'
services:
  stg:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    image: skripsi:${TAG}
    container_name: skripsi_client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - npm-cache:/root/.npm
    ports:
      - "3000:3000"
  prod:
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    image: clientSkripsi:${TAG}-production
    container_name: skripsi_client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - npm-cache/root/.npm
    ports:
      - "3000:3000"
  dev:
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    image: clientSkripsi:${TAG}-development
    container_name: skripsi_client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - npm-cache/root/.npm
    ports:
      - "3000:3000"
volumes:
  npm-cache:
    external: false
